### ISSUE TITLE
cubed `Array` vs `cubed.CoreArray`

### ISSUE THREAD

**Issue by TomNicholas** [tomwhite/cubed#123]
Hi, I'm just a bit confused by what the difference is between the `Array` object defined in `cubed.array_api.array_object` and the `cubed.CoreArray` that is returned by `cubed.from_array` and `asarray`. `CoreArray` doesn't implement the numpy API, but `Array` isn't importable from `cubed`'s top-level namespace.

Is this deliberate or should things be changed so that the only type a user sees is `Array`?

**Comment by tomwhite** [comment]
This does seem wrong - thanks for raising it. 

> Is this deliberate or should things be changed so that the only type a user sees is `Array`?

Yes. `Array` should be the type in the the top-level namespace and the user-facing documentation. `CoreArray` is an internal implementation detail.
