### ISSUE TITLE
dask still in requirements.txt

### ISSUE THREAD

**Issue by TomNicholas** [tomwhite/cubed#158]
I noticed that dask is still listed in the `requirements.txt` (and `requirements_modal.txt`). Is that deliberate or should it have been removed as part of https://github.com/tomwhite/cubed/commit/bcdaeb4328794d1979f612aa469ed10433645519?

**Comment by tomwhite** [comment]
The Dask dependency should be removed from `requirements.txt` and `setup.cfg` (I thought I had, but obviously I didn't). I'll fix that.

Rechunker depends on Dask, as you say, but in the vendored version of Rechunker in this repo I removed it's dependency (see 65b99eccf3bc967341c2a6c80edb47f9d74cfc62).

So, I think you should be able to install Cubed 0.6.0, uninstall Dask, and then you should be able to run Cubed OK.

**Comment by TomNicholas** [comment]
> So, I think you should be able to install Cubed 0.6.0, uninstall Dask, and then you should be able to run Cubed OK.

Thanks @tomwhite - that works for now, and has helped me find places where my xarray PR still imports dask. I still think we might want to pursue https://github.com/pangeo-data/rechunker/issues/139 though, if only for setting up testing CI environments in `cubed-xarray` (once I make that repo).
