### ISSUE TITLE
Package with conda

### ISSUE THREAD

**Issue by TomNicholas** [tomwhite/cubed#166]
The pangeo community primarily uses conda-forge, so we should put cubed up there.

**Comment by tomwhite** [comment]
Good idea. I'm not very familiar with conda packaging, is this something you could get started - or give some pointers?

**Comment by TomNicholas** [comment]
Cubed is [now available](https://anaconda.org/conda-forge/cubed) on conda - the [feedstock is here](https://github.com/conda-forge/cubed-feedstock).

My understanding is that now this will [automatically update](https://conda-forge.org/docs/maintainer/updating_pkgs.html) when a new release is uploaded to pypi. (We could automate releasing to pypi through github actions like xarray does, but that's another issue).

**Comment by tomwhite** [comment]
Opened #179 to automate releases
