### ISSUE TITLE
Example of running lithops using Google Cloud Functions

### ISSUE THREAD

**Issue by TomNicholas** [tomwhite/cubed#181]
**Can we add an example of how to deploy cubed on Google Cloud Functions using lithops?**

@tomwhite you asked what executor would be most useful to focus on for the purposes of early-stage pangeo testing. I think I said maybe Beam on Dataflow, but actually on reflection I think [Lithops on Google Cloud Functions](https://lithops-cloud.github.io/docs/source/compute_config/gcp_functions.html#test-lithops) might be the most useful right now, because:

a) A lot of the large pangeo datasets we would like to test on are currently available / only available in Google Cloud Storage ([see the catalog](https://catalog.pangeo.io/)),
b) My understanding is that beam on dataflow is likely slower than lithops, and lithops will better demonstrate cubed's serverless design,
c) Modal is invite-only.

I've started setting this up to test it out but am not sure how to set up a suitable docker container - neither the instructions for the lithops on AWS examples nor the Beam on dataflow examples seem to directly translate.

**Comment by tomwhite** [comment]
> Modal is invite-only.

Is it still? https://modal.com/signup seems to suggest you can sign-up directly.

Even so, having a GCP executor would be useful I think. GCP has both [Cloud Functions and Cloud Run](https://cloud.google.com/blog/topics/developers-practitioners/cloud-run-story-serverless-containers) - the former is higher-level, while the latter is more flexible. I'm not sure which is the better fit for Cubed so it might be worth trying both.

Cloud Run uses a docker file - see the example here https://github.com/lithops-cloud/lithops/tree/master/runtime/gcp_cloudrun. I think it could be adapted to include what Cubed's dockerfile for AWS lambda uses.

Cloud Functions uses a requirements.txt file (so pip only) - see https://github.com/lithops-cloud/lithops/tree/master/runtime/gcp_functions.

**Comment by TomNicholas** [comment]
> Is it still? https://modal.com/signup seems to suggest you can sign-up directly.

That's news to me! (I do already have access)

> Even so, having a GCP executor would be useful I think. GCP has both [Cloud Functions and Cloud Run](https://cloud.google.com/blog/topics/developers-practitioners/cloud-run-story-serverless-containers) - the former is higher-level, while the latter is more flexible. I'm not sure which is the better fit for Cubed so it might be worth trying both.

After some messing around @cissacstern and I managed to get the `lithops-add-asarray.py` example to run on Google Cloud Functions!

It actually turned out to be very simple - at least once we saw the link on building a lithops runtime you sent Tom :sweat_smile:

You basically just need to pass in a lithops configuration that looks like this:
```yaml
lithops:
    backend: gcp_functions
    storage: gcp_storage

gcp:
    region: us-east1
    credentials_path: /home/tom/Documents/Work/Code/experimentation/cubed_xarray_blog/lithops_gcf/pangeo-forge-4967-28119df031a5.json

gcp_storage:
    storage_bucket: tomnicholas-lithops-config
```
build a lithops runtime like this

```bash
lithops runtime build -f requirements.txt cubed_runtime -b gcp_functions
```

then run the example script in the same way
```bash
python lithops-add-asarray.py "gs://cubed-tomnicholas-temp/zarr-temp" cubed_runtime
```

This setup is nice because docker was not required. I can submit a PR to add this as another example if you want @tomwhite ? 

We didn't try using Cloud Run, but is there an advantage to doing that? All of cubed's dependencies are available on pip.

**Comment by tomwhite** [comment]
> After some messing around @cisaacstern and I managed to get the `lithops-add-asarray.py` example to run on Google Cloud Functions!

Awesome!

> I can submit a PR to add this as another example if you want @tomwhite ?

Yes please, that would be great.

> We didn't try using Cloud Run, but is there an advantage to doing that? All of cubed's dependencies are available on pip.

If Cloud Functions works well then that's fine.
