### ISSUE TITLE
Deleting intermediate data from cloud stores

### ISSUE THREAD

**Issue by tomwhite** [tomwhite/cubed#186]
Cubed creates intermediate Zarr files in the `work_dir` (see https://tom-e-white.com/cubed/generated/cubed.Spec.html). On a local machine this is typically a temporary directory that gets cleaned up by the OS.

On cloud stores the data does not get removed automatically. The way I have dealt with this is to use a separate bucket for intermediate data with a rule that deletes data after a certain time. We should add something in the docs about this.

For Google Cloud Storage, in the cloud console click on the bucket, then the "lifecycle" tab. Click "add a rule", select "delete object", then select "age" and enter "1" day. This will delete any data that is over 1 day old.

For AWS S3, there are some instructions in https://lepczynski.it/en/aws_en/automatically-delete-old-files-from-aws-s3/.

cc @TomNicholas

**Comment by TomNicholas** [comment]
This should definitely be added as a warning in the docs.

The warning also applies if you're running local tests, so you don't accidentally fill your laptop's SSD with 243GB of random Zarr data like I did last week :sweat_smile:

**Comment by tomwhite** [comment]
Fixed in #201
