### ISSUE TITLE
NotImplementedError: Slice step must be 1

### ISSUE THREAD

**Issue by TomNicholas** [tomwhite/cubed#196]
![Screenshot from 2023-06-01 14-24-14](https://github.com/tomwhite/cubed/assets/35968931/b1184a42-fead-44dc-82da-c5065e7d32a4)

**Comment by tomwhite** [comment]
We could implement this for `step > 1` by making the output chunks be `1/step` of the size of the input in the indexed dimension. This would ensure that the output chunk doesn't read from a potentially large number of input chunks if `step` was large (100 in this case), which could be slow and unreliable. We could follow with a rechunk to restore the original chunk size. I think the hardest bit would be doing the indexing arithmetic.

Are you blocked on this or did you find a workaround @TomNicholas?

Also, note there's a [test](https://github.com/tomwhite/cubed/blob/6d37febd3928c92cd89c94a2cd45ea4b435c1a3c/cubed/tests/test_array_api.py#L232-L235) covering this case (it currently just checks for `NotImplementedError`).
