### ISSUE TITLE
Running on a cluster

### ISSUE THREAD

**Issue by TomNicholas** [tomwhite/cubed#224]
It should be possible to try running Cubed on a cluster instead of on a serverless framework. Then the cluster just executes the tasks defined by the plan.

Writing a [dask executor for cubed](https://github.com/tomwhite/cubed/issues/161) would be one way to achieve this, but another might be to use [Lithops' Standalone Mode](https://github.com/lithops-cloud/lithops/blob/master/docs/source/execution_modes.rst#standalone-mode).

**Comment by tomwhite** [comment]
Closed by #241
