### ISSUE TITLE
Add type hints to blockwise and rechunk primitives

### ISSUE THREAD

**Issue by tomwhite** [tomwhite/cubed#230]
These would benefit from type hinting as an aid to understanding, and also to find bugs. This is especially true of the blockwise code, although it will be hard to specify good hints as there are a lot of nested structures and higher-order functions (this might be useful: https://peps.python.org/pep-0612/).

**Comment by TomNicholas** [comment]
I think this is important - it expect it will expose lots of subtle incompatibilities. Note I tried to fully type hint what the `ChunkManager` expects in xarray, for [the ABC](https://github.com/pydata/xarray/blob/86f99337d803866a4288fc7550f9ee8c495baf87/xarray/core/parallelcompat.py#L172), [dask](https://github.com/pydata/xarray/blob/86f99337d803866a4288fc7550f9ee8c495baf87/xarray/core/daskmanager.py#L35), and [cubed](https://github.com/xarray-contrib/cubed-xarray/blob/7c6c0493f11b16cc590c5abe442f19723d63c603/cubed_xarray/cubedmanager.py#L33).

Notice also that it's not even just types, there are multiple argument names that are different between dask and cubed (e.g. [`combine_func`](https://github.com/xarray-contrib/cubed-xarray/blob/7c6c0493f11b16cc590c5abe442f19723d63c603/cubed_xarray/cubedmanager.py#L81) versus [`combine`](https://github.com/pydata/xarray/blob/86f99337d803866a4288fc7550f9ee8c495baf87/xarray/core/daskmanager.py#L93) in `reduction`.)
