### ISSUE TITLE
Performance regression - `max_workers` not being used

### ISSUE THREAD

**Issue by TomNicholas** [tomwhite/cubed#235]
I'm pretty sure there was a performance regression in the last few weeks, which appears for the quadratic means workload on the timeline visualization:

Before:
![image](https://github.com/tomwhite/cubed/assets/35968931/b20ee881-3c67-4efc-92dc-4952a21a72ab)

After:
![image](https://github.com/tomwhite/cubed/assets/35968931/23fcdf11-238c-4a68-a429-2c2d9c597c3a)

Other things were changed too so perhaps ignore other aspects of this plot that are different, just notice that for some steps there is a group of tasks (exactly 334 out of 5334) that complete as a separate bunch later on. Looking at this again makes me wonder if this is actually instead some issue with the visualization...

@tomwhite you said you had an idea which commit might have caused this? If you tell me which one(s) you think is suspect can checkout a version prior to that and try it out now?

Ideally this sort of thing would be caught by an automated regression test, see #234.

**Comment by tomwhite** [comment]
> @tomwhite you said you had an idea which commit might have caused this? If you tell me which one(s) you think is suspect can checkout a version prior to that and try it out now?

Possibly #211.

I haven't merged it yet, but #217 is another change in a similar vein, but with a better implementation of backups.

**Comment by TomNicholas** [comment]
I checked out the commit immediately prior to #211, but still seeing the same problem

![Screenshot from 2023-06-27 14-20-31](https://github.com/tomwhite/cubed/assets/35968931/6d1e10fc-1518-488c-b11f-902151e1e613)

**Comment by tomwhite** [comment]
This looks like the case described in #222, which is a rechunk operation with two stages of 5000 and 334 tasks. You can check by seeing if there is an `array-139-intermediate` after running.

This isn't a new problem, but it may have arisen after changing memory settings.
