### ISSUE TITLE
Coiled Functions Executor

### ISSUE THREAD

**Issue by TomNicholas** [tomwhite/cubed#254]
Coiled has released a pseudo-serverless offering called [Coiled Functions](https://docs.coiled.io/user_guide/labs/run.html).

It seems like we could use it in a similar way to Modal stubs, but executing tasks in a similar way to the Dask Delayed Executor (#241). This might give a nice pseudo-serverless option which would benefit from the lower costs (of spot instance pricing vs serverless), but also not require the user to manually manager their Coiled cluster.

**Comment by tomwhite** [comment]
This looks great!
