### ISSUE TITLE
Simplify pipeline object to be single stage and non-optional mappable

### ISSUE THREAD

**Issue by tomwhite** [tomwhite/cubed#262]
Since #222 a [`CubedPipeline`](https://github.com/tomwhite/cubed/blob/01f8eb923feeb69ea74f39432572541825469054/cubed/primitive/types.py#L11C1-L20) will have just one [`Stage`](https://github.com/tomwhite/cubed/blob/01f8eb923feeb69ea74f39432572541825469054/cubed/vendor/rechunker/types.py#L73C1-L77), so there is no need to use a list.

Also, a `Stage` is always `mappable` in Cubed (we inherited from Rechunker, where it may not be)  so we can simplify by dropping the `Optional`.

So it would become something like:

```python
@dataclass(frozen=True)
class CubedPipeline:
    function: StageFunction
    name: str
    mappable: Iterable
    config: Config
    target_array: Any
    projected_mem: int
    num_tasks: int
    write_chunks: Optional[T_RegularChunks]
```

This would remove some checks from all our executors.

**Comment by TomNicholas** [comment]
:+1: I was confused as to why a stage would ever not be a Mappable.
